services:
  db:
    image: postgres:16
    container_name: devtrack-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: devtrack
    ports:
      - '5432:5432'
    volumes:
      - devtrack_pgdata:/var/lib/postgresql/data
volumes:
  devtrack_pgdata:
